dist: trusty
sudo: false
language: go
go:
- 1.7.5
notifications:
  email: false
env:
  global:
  - USERNAME=platyblog
  - REPO=platyblog.github.io
  - secure: iucsJo7pSqc2vUPIEzYy6XIOPde0O/FsSYuDGzaYpHdp7bUWT9aIH6UTFhyVI/u75MFaQWxOcLDK3P5A5aawfuALvkYn3PXUrhZV1YFuXBTQBwWX5l/BEy4UiM0gOOL6oCHBlNTiTIL7EasF8FsX7Re0nsfkSjfWS8MQbPUWW+srlOi4ix2mF5iKL93YknZkl1vub/OJdZtrRPP0klt6pqSZen3rBHZZ0tvuXHjsWwiTIaKghXc6nl8aseHnsU8jcDb8mV5EQDVmg5JXeP44ztB2PwtV7gxbGMvVpKwDnLDUvS5u25r8G17Fd4idtYM/hzin/lhjq8X+xPPFuIcHxhnJTYKrd63mJwP06Pq1bXo3nT9ZVfNQhBjAW4zUtU+4YuGL1GmaPh5z64NHZDasxKavOo2k4+CEMwyS7BbbdAp2Y+375sIodsFKypSX3jt+oCPrzQ2H1NOQ6GGw1WOzOLtmYz7hsn8Xv4uLDdUjw2CMeDXw+3B0kF8ZNbDRW2SOLLD13aVbHeY1hYLWo+j+oIe2DPbWK3QZANSOPrLNUqK4pGi5XjVhe79fBRH6NsZ9cCqBlxo3KC5/DHB/nedz7rJPz8NwpXMDJI8m+Ck6Qp3N5WrXN3UXXRumrGWYwg8RMk+l/dNFgrW1UFE/s9E0xZjAZIN5qdJPm8b+SaunBek=
before_script:
- git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
- go get -u -v github.com/spf13/hugo
script:
- hugo
after_success:
- cd public
- git init
- git config user.name "Travis Worker"
- git config user.email "travis@travis-ci.org"
- git remote add upstream https://$GH_TOKEN@github.com/$USERNAME/$REPO.git > /dev/null
  2>&1
- git fetch upstream
- git reset upstream/master
- git add -A .
- git commit -m "Update $(date '+%m/%d/%y %H:%M')."
- git push -q upstream HEAD:master > /dev/null 2>&1
